permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: polandeme
  email: polandeme@gmail.com
  link: http://polande.com
  weibo: http://weibo.com/chinahgr
  github: http://github.com/polandeme

# 站点信息
title: 前端 
description: 整理推荐前端.程序文章
url: https://polandeme.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
# favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
# ga:
#   id: UA-54767140-1
#   url: yansu.org

# disqus 设置
# disqus:
#   shortname: suyan-zh 
# https://github.com/suyan/suyan.github.io

comments :
    provider : duoshuo
    duoshuo :
      short_name : FEdaily